#!/bin/bash

#check if PYFILE env variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

#check if env variable already exists
if [ ! -f "$PYFILE" ]; then
    echo  "Error: Python file '$PYFILE' not found."
    exit 1

fi

#Run the Python script
python "$PYFILE"
